# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8be011ba135789ee01c1cf017b2096aaa97132ffd20fc14abab3f89c867edc25a26419c813e35d2ec19f5616bdd29b5c00fb0a58987757cd29630553fc72f335

test:
  secret_key_base: 69a501159cfe17ce3f3f7686c90dc35528a4389f51ce6ac217bfeb74269a1076014d78acaa8a7b5deeaa9a4495702361b8a9addc6b0d41885081d56b91ae50a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
